Fix question creation for choice questions
pkoerner/expert-parakeet pull request #179
Opened 2024-08-07 18:32 UTC by iTitus

Closes #177

2024-08-08 15:58 UTC, iTitus commented
Prev: ![image](https://github.com/user-attachments/assets/2e51ebb0-8f26-4c31-aefc-b969f2fd0d81)

New: ![image](https://github.com/user-attachments/assets/75b4d62f-b2ea-4c19-808d-611bf98dd00c)

It still looks a bit cramped and the legend/labels are of different sizes, but the functionality is strictly better.

2024-08-12 08:52 UTC, davrad requested changes
Looks good to me. Please add comments

2024-08-12 08:52 UTC, davrad commented on src/clj/services/question_service/question_service.clj
> +(defn- as-coll
Documentation for function is missing

2024-08-12 08:52 UTC, davrad commented on src/clj/services/question_service/question_service.clj
> +  [[:type (fn [_ value]
Documentation for function is missing

2024-08-12 08:52 UTC, davrad commented on src/clj/services/question_service/question_service.clj
> +  [_ question-form-data]
Comment is missing

2024-08-12 08:52 UTC, davrad commented on src/clj/views/question/create_question_view.clj
> +(defn- as-coll
Same as above

2024-08-12 08:52 UTC, davrad commented on src/clj/views/question/create_question_view.clj
>  (defn- free-text-inputs
Comment is missing

2024-08-12 08:52 UTC, davrad commented on src/clj/views/question/create_question_view.clj
> +(defn- choice-input
Same as above

2024-08-12 08:52 UTC, davrad commented on src/clj/views/question/create_question_view.clj
>    [errors question-data]
Comment is missing

2024-08-12 08:52 UTC, davrad commented on src/clj/views/question/create_question_view.clj
>    [errors question-data]
Comment is missing

2024-08-12 08:52 UTC, davrad commented on src/clj/views/question/create_question_view.clj
>    [{:question/keys [possible-solutions]}]
Same as above

2024-08-12 08:52 UTC, davrad commented on src/cljs/expert_parakeet/question/create_question_view.cljs
> +(defn- gen-dom-id
comment is missing

2024-08-12 09:51 UTC, MrDinkleberg approved these changes
Das ist schön!

2024-08-12 09:54 UTC, davrad approved these changes

2024-08-12 09:58 UTC, merged